// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package wire03

// Injectors from wire_zinject.go:

// github.com/go-zing/gozz-doc-examples/wire03.Target
func Initialize_Target() (*Target, func(), error) {
	buffer := _wireBufferValue
	wire03_aop_io_Writer := _wireBytesBufferValue
	wire03_impl_aop_io_Writer := &_impl_aop_io_Writer{
		_aop_io_Writer: wire03_aop_io_Writer,
	}
	string2 := ProvideString()
	bool2 := _wireBoolValue
	wire03NullString := NullString{
		String: string2,
		Valid:  bool2,
	}
	int2 := _wireIntValue
	target := &Target{
		Buffer:     buffer,
		Writer:     wire03_impl_aop_io_Writer,
		NullString: wire03NullString,
		Int:        int2,
	}
	return target, func() {
	}, nil
}

var (
	_wireBufferValue      = Buffer
	_wireBytesBufferValue = Buffer
	_wireBoolValue        = Bool
	_wireIntValue         = Int
)

// github.com/go-zing/gozz-doc-examples/wire03.mockString
func Initialize_mock_mockString() (mockString, func(), error) {
	string2 := MockString()
	mockConfig := _wireMockConfigValue
	bool2 := mockConfig.Bool
	wire03MockString := mockString{
		String: string2,
		Valid:  bool2,
	}
	return wire03MockString, func() {
	}, nil
}

var (
	_wireMockConfigValue = mock
)
