// Code generated by gozz:doc github.com/go-zing/gozz. DO NOT EDIT.

package overview01

var (
	_types_doc = map[interface{}]map[string]string{
		(*BookService)(nil): _doc_BookService,
		(*QueryId)(nil):     _doc_QueryId,
		(*QueryBook)(nil):   _doc_QueryBook,
		(*FormBook)(nil):    _doc_FormBook,
		(*Book)(nil):        _doc_Book,
		(*ListBook)(nil):    _doc_ListBook,
	}

	_doc_BookService = map[string]string{
		"":       "Book manager service",
		"Get":    "Get book entity by id",
		"List":   "Get book entities list by query params",
		"Create": "Create book entity with form",
		"Edit":   "Edit book entity from form",
		"Delete": "Delete book entity by id",
	}

	_doc_QueryId = map[string]string{
		"": "Uri path id param",
	}

	_doc_QueryBook = map[string]string{
		"":         "Query book entities param",
		"PageNo":   "Query pagination offser no",
		"PageSize": "Query pagination size",
	}

	_doc_FormBook = map[string]string{
		"":      "Form to edit or create book entity",
		"Title": "Title of book entity",
		"Type":  "Type of book entity",
	}

	_doc_Book = map[string]string{
		"":          "Book entity",
		"CreatedAt": "Book entity create time",
		"CreatedBy": "Book entity create user",
		"UpdatedAt": "Book entity last update time",
		"UpdatedBy": "Book entity last update user",
	}

	_doc_ListBook = map[string]string{
		"":      "Book entities list",
		"Total": "Query pagination total count in database",
		"List":  "Entities list data",
	}
)

func (QueryId) FieldDoc(f string) string { return _doc_QueryId[f] }

func (QueryBook) FieldDoc(f string) string { return _doc_QueryBook[f] }

func (FormBook) FieldDoc(f string) string { return _doc_FormBook[f] }

func (Book) FieldDoc(f string) string { return _doc_Book[f] }

func (ListBook) FieldDoc(f string) string { return _doc_ListBook[f] }
