// Code generated by gozz:wire github.com/go-zing/gozz. DO NOT EDIT.

//go:build wireinject
// +build wireinject

package overview02

import (
	wire "github.com/google/wire"
)

// github.com/go-zing/gozz-doc-examples/overview02.Application
func Initialize_Application(Config) (Application, func(), error) {
	panic(wire.Build(_Set))
}
