// Code generated by gozz:wire github.com/go-zing/gozz. DO NOT EDIT.

//go:build wireinject
// +build wireinject

package overview02

import (
	wire "github.com/google/wire"
)

var (
	_Set = wire.NewSet(
		// github.com/go-zing/gozz-doc-examples/overview02.Config
		wire.FieldsOf(new(Config), "Redis", "Server", "Sql"),

		// github.com/go-zing/gozz-doc-examples/overview02.ProvideHttpServer
		ProvideHttpServer,

		// github.com/go-zing/gozz-doc-examples/overview02.ProvideSql
		ProvideSql,

		// github.com/go-zing/gozz-doc-examples/overview02.ProvideRedisStore
		ProvideRedisStore,

		// github.com/go-zing/gozz-doc-examples/overview02.ServerHandlerImpl
		wire.Bind(new(_aop_ServiceHandler), new(*ServerHandlerImpl)),
		wire.Struct(new(_impl_aop_ServiceHandler), "*"),
		wire.Bind(new(ServiceHandler), new(*_impl_aop_ServiceHandler)),
		wire.Struct(new(ServerHandlerImpl), "*"),

		// github.com/go-zing/gozz-doc-examples/overview02.application
		wire.Bind(new(Application), new(*application)),
		wire.Struct(new(application), "*"),
	)
)
